# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkghtag < Formula
  desc "Create GitHub Tags via API"
  homepage "https://github.com/suzuki-shunsuke/mkghtag"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.1/mkghtag_darwin_amd64.tar.gz"
      sha256 "f723f43e7e7b8bae1006ce7f02bc7459a6a24cd3475bb3fb12c5964a4ecd504d"

      def install
        bin.install "mkghtag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.1/mkghtag_darwin_arm64.tar.gz"
      sha256 "59997aa75d89c96a5722330df179b6a1cddf36db3138aa3673628931d43186e6"

      def install
        bin.install "mkghtag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.1/mkghtag_linux_arm64.tar.gz"
      sha256 "d904d09fb4d053e51083e7c9e6e0eab2fb4d410bd3fabe24d954cc5385e1d316"

      def install
        bin.install "mkghtag"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.1/mkghtag_linux_amd64.tar.gz"
      sha256 "e5c62bff254bcd4d9bb143e589519757a44aba05ade67a5e8a4a08c8f741aac2"

      def install
        bin.install "mkghtag"
      end
    end
  end

  test do
    system "#{bin}/mkghtag --version"
  end
end
