# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkghtag < Formula
  desc "Create GitHub Tags via API"
  homepage "https://github.com/suzuki-shunsuke/mkghtag"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.6/mkghtag_darwin_amd64.tar.gz"
      sha256 "76ecc5cd597c855e00f34b96387a1275f22db29dd08e7cc14ddd582f5b4f2b62"

      def install
        bin.install "mkghtag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.6/mkghtag_darwin_arm64.tar.gz"
      sha256 "bd916876ffcc75757fc6ecf9d103aeab8d0e40690443092824dd0529f691d7c4"

      def install
        bin.install "mkghtag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.6/mkghtag_linux_amd64.tar.gz"
        sha256 "eff119f5bd3da912bf7fa4dbfc23d57a122b99a0e435670b3e75216587b79f61"

        def install
          bin.install "mkghtag"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.6/mkghtag_linux_arm64.tar.gz"
        sha256 "511d44e4460c57b67c52ba571254a3844af9595f5100f1fd370a0197c10b0600"

        def install
          bin.install "mkghtag"
        end
      end
    end
  end

  test do
    system "#{bin}/mkghtag --version"
  end
end
