# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkghtag" do
  name "mkghtag"
  desc "Create GitHub Tags via API"
  homepage "https://github.com/suzuki-shunsuke/mkghtag"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkghtag"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_darwin_amd64.tar.gz"
      sha256 "b21bf4896cfb37d09fd865d843b153f46d8fec2be6e790368cd82be59b8bfecf"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_darwin_arm64.tar.gz"
      sha256 "9637bc4672e4be29bbed9fca566f2749fb73d4016f6d34647f8b4ca4ef50dce8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_linux_amd64.tar.gz"
      sha256 "0f6600c8822b4b784bcf58b46212df7e1a97e4622e3f8db376b98affb7e84540"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_linux_arm64.tar.gz"
      sha256 "3d9059127db3603092a141e6b99f41e27b10a73ddfdfa10b5ccf27b3e2d50747"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkghtag"]
    end
  end

  # No zap stanza required
end
