# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkghtag" do
  desc "Create GitHub Tags via API"
  homepage "https://github.com/suzuki-shunsuke/mkghtag"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkghtag"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.8/mkghtag_darwin_amd64.tar.gz"
      sha256 "e20788f12216f58c4d361f46cc73d7a50c83934a78e7b316855487e8cb34583d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.8/mkghtag_darwin_arm64.tar.gz"
      sha256 "5524adb65db1d21d456c2121d975077c89d416e2ffda939c138d43d79024a7ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.8/mkghtag_linux_amd64.tar.gz"
      sha256 "6dcc29e810291818f279ac9251f1dbbd477c5ee906f0b42606799e4c77c1b62d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v0.1.8/mkghtag_linux_arm64.tar.gz"
      sha256 "07ea3aa12d15e58da86a80dc36d9f67d6cc9dec785e8f0ec4cdcda8779986762"
    end
  end

  # No zap stanza required
end
