# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkghtag" do
  name "mkghtag"
  desc "Create GitHub Tags via API"
  homepage "https://github.com/suzuki-shunsuke/mkghtag"
  version "0.1.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkghtag"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_darwin_amd64.tar.gz"
      sha256 "cf36ad0bbce0b52405b4539111860034f1ceb59d805567d67ba9feb42781bcb3"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_darwin_arm64.tar.gz"
      sha256 "19e07430749ef83b02bf5d7432395d84bdc7ee833d02208fe8e585c0d7d4356b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_linux_amd64.tar.gz"
      sha256 "d7e883b0d6201280fe734985c654fe6496e06bf8508a64f2661301c7c0db0472"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/mkghtag/releases/download/v#{version}/mkghtag_linux_arm64.tar.gz"
      sha256 "0a6e92f66d617815ff918d2e756123c9af9f14733d77e774f96528627db17a11"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkghtag"]
    end
  end

  # No zap stanza required
end
